<?php

namespace App\Services;

use Illuminate\Support\Collection;

class RbacPermissionService
{
    public static function groups(): array
    {
        return [
            'System' => [
                '*' => 'Full system access',
            ],
            'Dashboard' => [
                'dashboard.view' => 'View dashboard',
            ],
            'Employees' => [
                'employee.view' => 'View employees',
                'employee.create' => 'Create employees',
                'employee.edit' => 'Edit employees',
                'employee.delete' => 'Delete employees',
            ],
            'Tasks' => [
                'task.view' => 'View own tasks',
                'task.create' => 'Create own tasks',
                'task.edit' => 'Edit own tasks',
                'task.delete' => 'Delete own tasks',
                'task.assign' => 'Assign tasks to employees',
                'task.manage' => 'Manage all employee tasks',
            ],
            'Leave Management' => [
                'leave-management.view' => 'View leave management menu',
                'leave-request.view' => 'View leave requests',
                'leave-request.create' => 'Create leave requests',
                'leave-request.edit' => 'Edit leave requests',
                'leave-request.delete' => 'Delete leave requests',
                'leave-type.view' => 'View leave types',
                'leave-type.create' => 'Create leave types',
                'leave-type.edit' => 'Edit leave types',
                'leave-type.delete' => 'Delete leave types',
                'leave-setting.view' => 'View leave settings',
                'leave-setting.create' => 'Create leave settings',
                'leave-setting.edit' => 'Edit leave settings',
                'leave-setting.delete' => 'Delete leave settings',
                'holiday.view' => 'View holidays',
                'holiday.create' => 'Create holidays',
                'holiday.edit' => 'Edit holidays',
                'holiday.delete' => 'Delete holidays',
            ],
            'Payroll' => [
                'payroll.view' => 'View payrolls',
                'payroll.create' => 'Create payrolls',
                'payroll.edit' => 'Edit payrolls',
                'payroll.delete' => 'Delete payrolls',
                'payroll-period.view' => 'View payroll periods',
                'payroll-period.create' => 'Create payroll periods',
                'payroll-period.edit' => 'Edit payroll periods',
                'payroll-period.delete' => 'Delete payroll periods',
            ],
            'Reports' => [
                'report.performance.view' => 'View performance report',
                'report.attendance.view' => 'View attendance report',
                'report.leave.view' => 'View leave report',
                'activity-log.view' => 'View activity logs',
            ],
            'Performance' => [
                'performance.view' => 'View performance menu',
                'kpi.view' => 'View KPI',
                'kpi.create' => 'Create KPI',
                'kpi.edit' => 'Edit KPI',
                'kpi.delete' => 'Delete KPI',
                'feedback360.view' => 'View 360 feedback',
                'feedback360.create' => 'Give 360 feedback',
                'feedback360.edit' => 'Edit 360 feedback',
                'feedback360.delete' => 'Delete 360 feedback',
            ],
            'Transfer' => [
                'transfer.view' => 'View transfers',
                'transfer.create' => 'Create transfers',
                'transfer.edit' => 'Edit transfers',
                'transfer.delete' => 'Delete transfers',
                'transfer-type.view' => 'View transfer types',
                'transfer-type.create' => 'Create transfer types',
                'transfer-type.edit' => 'Edit transfer types',
                'transfer-type.delete' => 'Delete transfer types',
            ],
            'Facilities' => [
                'facility.view' => 'View facilities',
                'facility.create' => 'Create facilities',
                'facility.edit' => 'Edit facilities',
                'facility.delete' => 'Delete facilities',
                'facility-criteria.view' => 'View facility criteria',
                'facility-criteria.create' => 'Create facility criteria',
                'facility-criteria.edit' => 'Edit facility criteria',
                'facility-criteria.delete' => 'Delete facility criteria',
            ],
            'Communication' => [
                'notification.view' => 'View notifications',
                'notification.create' => 'Create notifications',
                'notification.edit' => 'Edit notifications',
                'notification.delete' => 'Delete notifications',
                'chat.view' => 'View chats',
                'chat.create' => 'Create chats',
                'chat.edit' => 'Edit chats',
                'chat.delete' => 'Delete chats',
            ],
            'Attendance' => [
                'attendance.view' => 'View attendance',
                'attendance.import' => 'Import attendance',
                'attendance.export' => 'Export attendance',
            ],
            'Organization' => [
                'organization.view' => 'View organization data',
                'organization.create' => 'Create organization data',
                'organization.edit' => 'Edit organization data',
                'organization.delete' => 'Delete organization data',
                'company.view' => 'View companies',
                'company.create' => 'Create companies',
                'company.edit' => 'Edit companies',
                'company.delete' => 'Delete companies',
                'department.view' => 'View departments',
                'department.create' => 'Create departments',
                'department.edit' => 'Edit departments',
                'department.delete' => 'Delete departments',
                'division.view' => 'View divisions',
                'division.create' => 'Create divisions',
                'division.edit' => 'Edit divisions',
                'division.delete' => 'Delete divisions',
                'section.view' => 'View sections',
                'section.create' => 'Create sections',
                'section.edit' => 'Edit sections',
                'section.delete' => 'Delete sections',
                'work-location.view' => 'View work locations',
                'work-location.create' => 'Create work locations',
                'work-location.edit' => 'Edit work locations',
                'work-location.delete' => 'Delete work locations',
            ],
            'Reference' => [
                'reference.view' => 'View reference data',
                'reference.create' => 'Create reference data',
                'reference.edit' => 'Edit reference data',
                'reference.delete' => 'Delete reference data',
                'level.view' => 'View levels',
                'level.create' => 'Create levels',
                'level.edit' => 'Edit levels',
                'level.delete' => 'Delete levels',
                'job-position.view' => 'View job positions',
                'job-position.create' => 'Create job positions',
                'job-position.edit' => 'Edit job positions',
                'job-position.delete' => 'Delete job positions',
                'religion.view' => 'View religions',
                'religion.create' => 'Create religions',
                'religion.edit' => 'Edit religions',
                'religion.delete' => 'Delete religions',
                'contract-type.view' => 'View contract types',
                'contract-type.create' => 'Create contract types',
                'contract-type.edit' => 'Edit contract types',
                'contract-type.delete' => 'Delete contract types',
                'education-type.view' => 'View education types',
                'education-type.create' => 'Create education types',
                'education-type.edit' => 'Edit education types',
                'education-type.delete' => 'Delete education types',
                'family-type.view' => 'View family types',
                'family-type.create' => 'Create family types',
                'family-type.edit' => 'Edit family types',
                'family-type.delete' => 'Delete family types',
                'relationship.view' => 'View relationships',
                'relationship.create' => 'Create relationships',
                'relationship.edit' => 'Edit relationships',
                'relationship.delete' => 'Delete relationships',
                'document-type.view' => 'View document types',
                'document-type.create' => 'Create document types',
                'document-type.edit' => 'Edit document types',
                'document-type.delete' => 'Delete document types',
                'shift.view' => 'View shifts',
                'shift.create' => 'Create shifts',
                'shift.edit' => 'Edit shifts',
                'shift.delete' => 'Delete shifts',
                'approval-workflow.view' => 'View approval workflows',
                'approval-workflow.create' => 'Create approval workflows',
                'approval-workflow.edit' => 'Edit approval workflows',
                'approval-workflow.delete' => 'Delete approval workflows',
                'role.view' => 'View roles',
                'role.create' => 'Create roles',
                'role.edit' => 'Edit roles',
                'role.delete' => 'Delete roles',
                'module.view' => 'View modules',
                'module.create' => 'Create modules',
                'module.edit' => 'Edit modules',
                'module.delete' => 'Delete modules',
            ],
            'Administration' => [
                'administration.view' => 'View administration menu',
                'user-role.view' => 'View user role assignments',
                'user-role.create' => 'Assign user roles',
                'user-role.edit' => 'Edit user role assignments',
                'user-role.delete' => 'Remove user role assignments',
                'settings.view' => 'View settings',
                'settings.edit' => 'Edit settings',
                'documentation.view' => 'View documentation',
                'login-attempt.view' => 'View login attempts',
            ],
        ];
    }

    public static function keys(): array
    {
        return Collection::make(self::groups())
            ->flatMap(fn (array $permissions) => array_keys($permissions))
            ->values()
            ->all();
    }
}
