@extends('layouts.app')

@section('title', 'Shifts - ' . config('app.name'))

@section('content')
<div x-data="{ open: false, edit: false, item: {}, deleteId: null }" class="space-y-6">
    <div class="flex items-center justify-between"><div><h2 class="text-2xl font-bold text-gray-900 dark:text-white">Shifts</h2><p class="mt-1 text-sm text-gray-600 dark:text-gray-400">Manage work shift schedules.</p></div><button @click="open = true; edit = false; item = {}" class="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-xl">Add New</button></div>
    @session('success')<div class="p-4 bg-green-50 dark:bg-green-900/30 border border-green-200 dark:border-green-800 rounded-xl text-sm text-green-700 dark:text-green-300">{{ $value }}</div>@endsession
    <x-list-search :action="route('master-data.shifts')" placeholder="Search shift name" />
    <div class="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 overflow-hidden shadow-sm"><table class="w-full text-sm"><thead><tr class="bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700"><th class="text-left px-6 py-4 font-semibold text-gray-900 dark:text-white">Name</th><th class="text-left px-6 py-4 font-semibold text-gray-900 dark:text-white">Work Time</th><th class="text-left px-6 py-4 font-semibold text-gray-900 dark:text-white">Break</th><th class="text-right px-6 py-4 font-semibold text-gray-900 dark:text-white">Actions</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-700">@forelse($shifts as $shift)<tr><td class="px-6 py-4 text-gray-900 dark:text-white font-medium">{{ $shift->name }}</td><td class="px-6 py-4 text-gray-600 dark:text-gray-400">{{ $shift->start_time }} - {{ $shift->end_time }}</td><td class="px-6 py-4 text-gray-600 dark:text-gray-400">{{ $shift->break_start ?? '-' }} - {{ $shift->break_end ?? '-' }}</td><td class="px-6 py-4 text-right"><button @click="open = true; edit = true; item = { id: {{ $shift->id }}, name: @js($shift->name), start_time: @js(substr($shift->start_time, 0, 5)), end_time: @js(substr($shift->end_time, 0, 5)), break_start: @js($shift->break_start ? substr($shift->break_start, 0, 5) : ''), break_end: @js($shift->break_end ? substr($shift->break_end, 0, 5) : '') }" class="text-indigo-600 dark:text-indigo-400 font-medium mr-3">Edit</button><button @click="deleteId = {{ $shift->id }}" class="text-red-600 dark:text-red-400 font-medium">Delete</button></td></tr>@empty<tr><td colspan="4" class="px-6 py-12 text-center text-gray-500 dark:text-gray-400">No shifts found.</td></tr>@endforelse</tbody></table>@if($shifts->hasPages())<div class="px-6 py-4 border-t border-gray-200 dark:border-gray-700">{{ $shifts->links() }}</div>@endif</div>
    <div x-show="open" x-cloak class="fixed inset-0 z-50 flex items-center justify-center p-4"><div class="fixed inset-0 bg-gray-900/50" @click="open = false"></div><div class="relative bg-white dark:bg-gray-800 rounded-2xl shadow-xl border border-gray-200 dark:border-gray-700 w-full max-w-lg p-6"><h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4" x-text="edit ? 'Edit Shift' : 'Add Shift'"></h3><form method="POST" :action="edit ? `/master-data/shifts/${item.id}` : '{{ route('master-data.shifts.store') }}'">@csrf<input type="hidden" name="_method" :value="edit ? 'PUT' : 'POST'"><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><input name="name" x-model="item.name" required placeholder="Name" class="md:col-span-2 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"><input type="time" name="start_time" x-model="item.start_time" required class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"><input type="time" name="end_time" x-model="item.end_time" required class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"><input type="time" name="break_start" x-model="item.break_start" class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"><input type="time" name="break_end" x-model="item.break_end" class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"></div><div class="flex justify-end gap-3 mt-6"><button type="button" @click="open = false" class="px-4 py-2 text-sm bg-gray-100 dark:bg-gray-700 rounded-lg">Cancel</button><button class="px-4 py-2 text-sm text-white bg-indigo-600 rounded-lg" x-text="edit ? 'Update' : 'Save'"></button></div></form></div></div>
    <div x-show="deleteId" x-cloak class="fixed inset-0 z-50 flex items-center justify-center p-4"><div class="fixed inset-0 bg-gray-900/50" @click="deleteId = null"></div><div class="relative bg-white dark:bg-gray-800 rounded-2xl shadow-xl border border-gray-200 dark:border-gray-700 w-full max-w-md p-6 text-center"><h3 class="text-lg font-semibold text-gray-900 dark:text-white">Confirm Delete</h3><form :action="`/master-data/shifts/${deleteId}`" method="POST" class="flex justify-center gap-3 mt-6">@csrf @method('DELETE')<button type="button" @click="deleteId = null" class="px-4 py-2 text-sm bg-gray-100 dark:bg-gray-700 rounded-lg">Cancel</button><button class="px-4 py-2 text-sm text-white bg-red-600 rounded-lg">Delete</button></form></div></div>
</div>
@endsection
